Version                              = 0x287

[General]
OutputAPI                            = d3d11_fl10_0
Adapters                             = all
FullScreenMode                       = true

InheritColorProfileInFullScreenMode  = true

[DirectX]
dgVoodooWatermark                   = false
VideoCard                           = internal3D
VRAM                                = 128
Resolution                          = unforced
; Antialiasing                        = 2x

AppControlledScreenMode             = true
DisableAltEnterToToggleScreenMode   = true

[DirectXExt]
AdapterIDType                       = nvidia
VendorID                            = 0x10DE
DeviceID                            = 0x0200

DeferredScreenModeSwitch            = false

[GeneralExt]
WindowedAttributes			= Borderless, AlwaysOnTop, FullscreenSize
FullscreenAttributes                = fake
