#!/usr/bin/env python3
"""Create placeholder assets so the setup script compiles without the real game data.

The real assets (data/, internal/media, internal/misc, internal/runtime, tools/) are not
versioned. This script scans .iss files for every referenced source file and creates a small
dummy for each missing one, so CI (and contributors without the full data set) can run ISCC as
a syntax/consistency check. Existing files are never overwritten.

An installer built from placeholders is useless and must never be distributed.

Usage:
  python ci/make_placeholder_assets.py [--root DIR] [--list] [INPUT ...]

INPUT is a .iss file or a directory whose *.iss files are scanned (default: the repo root).
Paths that are only built by ISPP macros are invisible in the raw scripts, so CI passes the fully
preprocessed script of every variant instead (dumped with `#expr SaveToFile(...)`, see
ci/build.ps1), which contains every resolved path.

--list only prints the required asset paths (one per line, relative to the root, "*" for a
wildcard source) and creates nothing: use it as the asset manifest of a variant.
"""
import argparse
import re
import struct
import sys
from pathlib import Path

# Asset folders that are gitignored and therefore need placeholders.
ASSET_PREFIXES = ("data\\", "internal\\media\\", "internal\\misc\\", "internal\\runtime\\", "tools\\")

SOURCE_RE = re.compile(r'Source:\s*"([^"]+)"', re.IGNORECASE)
SETUP_FILE_RE = re.compile(
    r"^\s*(SetupIconFile|WizardImageFile|WizardSmallImageFile|LicenseFile|InfoBeforeFile|InfoAfterFile)\s*=\s*(.+?)\s*$",
    re.IGNORECASE,
)
# Paths used from Pascal code / ISPP (e.g. ExtractTemporaryFile, #define ... "internal\...")
QUOTED_ASSET_RE = re.compile(r"""['"]((?:data|internal\\(?:media|misc|runtime)|tools)\\[^'"]+\.[A-Za-z0-9]{2,5})['"]""", re.IGNORECASE)

PLACEHOLDER_TEXT = b"placeholder generated by ci/make_placeholder_assets.py - not a real asset\n"


def minimal_bmp(width=8, height=8):
    row = (width * 3 + 3) & ~3
    pixels = b"\x80" * (row * height)
    header = struct.pack("<2sIHHI", b"BM", 54 + len(pixels), 0, 0, 54)
    info = struct.pack("<IiiHHIIiiII", 40, width, height, 1, 24, 0, len(pixels), 2835, 2835, 0, 0)
    return header + info + pixels


def minimal_ico():
    # 16x16 32bpp icon with an embedded BMP (header height doubled for the AND mask).
    w = h = 16
    xor = b"\x00\x00\x00\xff" * (w * h)
    and_mask = b"\x00" * (((w + 31) // 32) * 4 * h)
    bmp_info = struct.pack("<IiiHHIIiiII", 40, w, h * 2, 1, 32, 0, len(xor) + len(and_mask), 0, 0, 0, 0)
    image = bmp_info + xor + and_mask
    icondir = struct.pack("<HHH", 0, 1, 1)
    entry = struct.pack("<BBBBHHII", w, h, 0, 0, 1, 32, len(image), 6 + 16)
    return icondir + entry + image


def content_for(path: Path) -> bytes:
    # Inno Setup validates images and icons at compile time, so those get real minimal files.
    ext = path.suffix.lower()
    if ext == ".bmp":
        return minimal_bmp()
    if ext == ".ico":
        return minimal_ico()
    if ext == ".rtf":
        return b"{\\rtf1\\ansi placeholder}"
    return PLACEHOLDER_TEXT


def expand_defines(text: str) -> str:
    # Raw (not preprocessed) scripts only: give ISPP-built names a plausible value.
    return re.sub(r"\{#\s*CertFileName\s*\}", "cert_name.crt", text)


def collect(files):
    refs = set()
    for iss in files:
        text = iss.read_text(encoding="utf-8-sig", errors="replace")
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith(";") or stripped.startswith("//"):
                continue
            for m in SOURCE_RE.finditer(line):
                refs.add(expand_defines(m.group(1)))
            m = SETUP_FILE_RE.match(line)
            if m:
                refs.add(expand_defines(m.group(2)))
            for m in QUOTED_ASSET_RE.finditer(line):
                refs.add(expand_defines(m.group(1)))
    return refs


def asset_paths(refs):
    """Yield the relative asset paths (as tuples of parts) of all references in asset folders."""
    for ref in sorted(refs):
        norm = ref.replace("\\\\", "\\")
        if not norm.lower().startswith(ASSET_PREFIXES) or "{" in norm:
            continue
        yield tuple(p for p in norm.split("\\") if p)


def input_files(inputs, root):
    if not inputs:
        inputs = [root]
    files = []
    for item in inputs:
        path = Path(item)
        files.extend(sorted(path.glob("*.iss")) if path.is_dir() else [path])
    return files


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent,
                        help="repository root the asset paths are relative to (default: parent of ci/)")
    parser.add_argument("--list", action="store_true", help="only print the required asset paths")
    parser.add_argument("inputs", nargs="*", help=".iss files or directories to scan (default: the root)")
    args = parser.parse_args(argv)
    root = args.root.resolve()

    parts_list = list(asset_paths(collect(input_files(args.inputs, root))))
    if args.list:
        for parts in parts_list:
            print("\\".join(parts))
        return 0

    created = 0
    for parts in parts_list:
        rel = Path(*parts)
        if "*" in rel.name or "?" in rel.name:
            # Wildcard source: one file is enough for ISCC to find a match.
            target = root / rel.parent / "placeholder.txt"
        else:
            target = root / rel
        if target.exists():
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content_for(target))
        created += 1
    print(f"placeholder assets created: {created} (of {len(parts_list)} referenced asset paths)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
